# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/spring-ai-chat-client" # Location of package manifests
    schedule:
      interval: "weekly"

- package-ecosystem: "maven" # See documentation for possible values
    directory: "/spring-boot-bean-validation" # Location of package manifests
    schedule:
      interval: "weekly"

- package-ecosystem: "maven" # See documentation for possible values
    directory: "/spring-boot-global-exception-handling" # Location of package manifests
    schedule:
      interval: "weekly"

- package-ecosystem: "maven" # See documentation for possible values
    directory: "/spring-boot-internationalization-i18n" # Location of package manifests
    schedule:
      interval: "weekly"

- package-ecosystem: "maven" # See documentation for possible values
    directory: "/spring-security-oauth2-resource-server-credentials-jwt" # Location of package manifests
    schedule:
      interval: "weekly"
